/****** Script for SelectTopNRows command from SSMS  ******/
SELECT --top 100
	   dbo.CharPad (ISNULL( [Claim_Number]												, '' )		,12			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Line_number]												, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Member_Number]												, '' )		,9			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Dependent_Number]											, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Dependent_Name]											, '' )		,30			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Dependent_Birth]											, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Dependent_Sex]												, '' )		,1			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Dependent_SSN]												, '' )		,9			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Dependent_Relation]										, '' )		,1			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Status]													, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Received_Date]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Entered_Date]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Issued_Date]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Action_Date]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Cleared_Date]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Operator]													, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Draft]														, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Check_Number]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Assignment]												, '' )		,1			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Total_Claim_Payment]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Bill_Provider_TIN]											, '' )		,9			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Bill_Provider_Name]										, '' )		,30			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Bill_Provider_Address_Sequence]							, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Patient_Account_Number]									, '' )		,20			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Plan_Type]													, '' )		,7			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Group]														, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Fund]														, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Subgroup]													, '' )		,7			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Benefit_Plan]												, '' )		,7			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Coverage_Code]												, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [From_Date]													, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Thru_Date]													, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Procedure]													, '' )		,8			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Primary_Diagnosis]											, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Secondary_Diagnosis]										, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Place_of_Service]											, '' )		,2			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Type_of_Service]											, '' )		,2			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Benefit_Code]												, '' )		,5			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Quantity]													, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Billed_Amount]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Ineligible_Amount1]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Ineligible_Code1]											, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_Allowed]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Deductible_Type]											, '' )		,1			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_Deductible_1]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Deductible_Type2]											, '' )		,1			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_Deductible_2]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_Percentage]											, '' )		,5			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_Covered]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_COB_Adjustment]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_Net_Covered]											, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_Medical_Allowed]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Deductible_CopayCode]										, '' )		,1			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_Medical_CopayAmt]									, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Deductible_DeductibleCode]									, '' )		,1			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_Medical_Deductible_Amt]								, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_Medical_Percentage]									, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_Medical_Covered]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_Medical_COB_Adjustment]								, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_Medical_Net_Coverage]								, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Member_Pre-Paid]											, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Medicare_Pre-Paid]											, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Other_Insurance_Pre-Paid]									, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Discount_Definition]										, '' )		,7			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Discount_Amount]											, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Total_Line_Payment]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Schedule_Detail_Reference_Number]							, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Schedule_Master]											, '' )		,7			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [PPO]														, '' )		,7			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Tooth_Number]												, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Surface]													, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Line_Comment_1]											, '' )		,70			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Line_Comment_2]											, '' )		,70			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Claim_Comment_1]											, '' )		,70			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Claim_Comment_2]											, '' )		,70			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Attachment_Number]											, '' )		,20			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Hold_Code_1]												, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Hold_Code_1_Date]											, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Hold_Code_2]												, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Hold_Code_2_Date]											, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Hold_Code_3_]												, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Hold_Code_3_Date]											, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Billing_Address_1]											, '' )		,40			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Billing_Address_2]											, '' )		,40			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Billing_City]												, '' )		,20			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Billing_State]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Billing_Zip]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Service_Address_1]											, '' )		,40			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Service_Address_2]											, '' )		,40			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Service_City]												, '' )		,20			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Service_State]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Service_Zip]												, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Service_Address_Sequence_Number]							, '' )		,4			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Service_Provider_Name]										, '' )		,30			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Service_Provider_ID_Number]								, '' )		,9			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Svc_Prov_Sequence_Number]									, '' )		,4			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Illness-Diagnosis]											, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Illness-Incurred_date]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Illness_Sequence]											, '' )		,4			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Admission_Date]											, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Admission_Sequence]										, '' )		,4			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Tooth_Number_2]											, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Tooth_Number_3]											, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Tooth_Number_4]											, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Tooth_Number_5]											, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Surface_2]													, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Surface_3]													, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Surface_4]													, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Surface_5]													, '' )		,3			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Claim_Comment_3]											, '' )		,70			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Claim_Comment_4]											, '' )		,70			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Claim_Comment_5]											, '' )		,70			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_1]														, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_2]														, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_3]														, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_4]														, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_5]														, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_6]														, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_7]														, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_8]														, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_9]														, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_10]													, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_11]													, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_12]													, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_13]													, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_14]													, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_15]													, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_16]													, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_17]													, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_18]													, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_19]													, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [CDD_20]													, '' )		,100		,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_allowed_-_reversion]									, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_deductible_1_-_reversion]							, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_deductible_1_type_-_reversion]						, '' )		,1			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_deductible_2_-_reversion]							, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_deductible_2_type_-_reversion]						, '' )		,1			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_percentage_-_reversion]								, '' )		,5			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_gross_covered_-_reversion]							, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_cob_adjustment_-_reversion]							, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Basic_net_covered_-_reversion]								, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_medical_allowed_-_reversion]							, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_medical_deductible_1_-_reversion]					, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_medical_deductible_1_type_-_reversion]				, '' )		,1			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_medical_deductible_2_-_reversion]					, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_medical_deductible_2_type_-_reversion]				, '' )		,1			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_medical_percentage_-_reversion]						, '' )		,5			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_medical_gross_covered_-_reversion]					, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_medical_cob_adjustment_-_reversion]					, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Major_medical_net_covered_-_reversion]						, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Prior payment check]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [prior pymt adjustment]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [ineligible code 2]											, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [ineligible amount 2]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [ineligible code 3]											, '' )		,6			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [ineligible amount 3]										, '' )		,10			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Attachment type]											, '' )		,2			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [PrimaryDiagnosis2]											, '' )		,8			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Secondary Diagnosis2]										, '' )		,8			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Illness-Diagnosis2]										, '' )		,8			,'LEFT',' ')
      ,dbo.CharPad (ISNULL( [Filler]													, '' )		,10			,'LEFT',' ')
      --,dbo.CharPad ([LinkKey]													,1			,'LEFT',' ')
      --,dbo.CharPad ([UniqID]													,20			,'LEFT',' ')
      --,dbo.CharPad ([IDseq2]													,10			,'LEFT',' ')
      --,dbo.CharPad ([KEYFU2]													,12			,'LEFT',' ')
-- INTO clmt
 FROM [1240].[dbo].[clmdetailMiss2]
  order by IDseq2

 -- select * from clmt
  
  --select * from clmt order by clmt